fix container process with stdout killed by sigpipe when containerd was stopped
containerd/rust-extensions pull request #100
Opened 2022-10-20 15:33 UTC by zzyyzte

fix container process with stdout killed by sigpipe when containerd was stopped

2022-10-24 03:31 UTC, Burning1020 requested changes

2022-10-24 03:31 UTC, Burning1020 commented on crates/runc-shim/src/common.rs
> -        pio.copy = false;
Instead of piping io, we have a different direct IO solution: https://github.com/containerd/rust-extensions/pull/24#issuecomment-1040619960.

2022-10-24 03:43 UTC, Burning1020 commented
Could you add some details like bug description, containerd log output?

2023-07-19 16:40 UTC, mxpv commented
ping @zzyyzte are you still interested in contributing this?

2023-07-20 11:51 UTC, zzyyzte commented
yes, but I can't remember exactly how this problem came about...

2023-07-20 13:11 UTC, Burning1020 commented
@zzyyzte @mxpv I knew this problem exactly. This issus is caused by closing the "read" side of io fifo when containerd stopped. Read side should be opened in shim when is copy io is disabled. I'll fix this.

2023-07-24 17:43 UTC, closed without merging